### ISSUE TITLE
执行最后一步生成apidoc报错

### ISSUE THREAD

**Issue by xushaobo** [wmhello/laravel_template_with_vue#1]
$apidoc -i ./ -o public/apidoc/
报错如下：
...
warn: parser plugin 'returns' not found in block: 1
warn: parser plugin 'returns' not found in block: 2
warn: parser plugin 'returns' not found in block: 3
error: Undefined error. 
{ File: './node_modules/original/node_modules/url-parse/index.js',
  Block: 2,
  Element: '@constructor',
  Source: '@constructor\n@param {String} address URL we want to parse.' }

$apidoc -f .php -i ./ -o public/apidoc --debug
成功，显示如下
....
verbose: worker postProcess: apisuccesstitle
verbose: worker postProcess: apiuse
verbose: run filter
verbose: filter postFilter: apierror
verbose: filter postFilter: apiheader
verbose: filter postFilter: apiparam
verbose: filter postFilter: apisuccess
verbose: create dir: public/apidoc/
verbose: copy template /usr/local/nodejs/lib/node_modules/apidoc/template/ to: public/apidoc/
verbose: write json file: public/apidoc/api_data.json
verbose: write js file: public/apidoc/api_data.js
verbose: write json file: public/apidoc/api_project.json
verbose: write js file: public/apidoc/api_project.js
info: Done.

However when visit the url "http://backend.test/apidoc/"
shows Page Not Found

**Comment by xushaobo** [comment]
google-chorme file:///var/www/html/backend/public/apidoc/index.html
it goes right

**Comment by puzzle9** [comment]
其实你把 public/apidoc 这个文件夹删除后再运行就可以了……
