### ISSUE TITLE
Support for English language

### ISSUE THREAD

**Issue by connecteev** [wmhello/laravel_template_with_vue#10]
Hi @wmhello thank you for this repo. I haven't installed and tested it out yet, but based on the popularity it may be what I am looking for.
The problem is, I am not a Chinese speaker and find understanding the code, instructions etc (even the screenshots) next to impossible. If you speak English or know someone that does, would it be possible to provide support for English language in both Laravel (back end) and Vue front end)?
I can help with some of the translation (I have good English speaking-skills) if I get some technical guidance on *where* in the code the translations should go.

**Comment by lsk02** [comment]
i can translate it

**Comment by wmhello** [comment]
那以后去做个国际化吧

**Comment by wmhello** [comment]
later
