### ISSUE TITLE
前端报错，后端请求token的时候卡死

### ISSUE THREAD

**Issue by 956569011** [wmhello/laravel_template_with_vue#32]
前端报这个错 vue-router.esm.js:1921 Error: Cannot find module '@/views/login/index'

**Comment by wmhello** [comment]
可以联系我  使用微信（xpyzwm）  我这边没有问题  要看看你实际的情况才能做调整

**Comment by wmhello** [comment]
看到信息后  联系  我这边先关闭了  v3版本一致在测试  发现没有问题
