### ISSUE TITLE
api有点问题，guzzlehttp这个包卡死了

### ISSUE THREAD

**Issue by tonyxyl** [wmhello/laravel_template_with_vue#4]
`Route::post('/login', 'Auth\LoginController@login')->name('login.login');`
这条路由, 我看到你用了GuzzleHttp/guzzle这个包来发送网络请求, 我本地环境单独测试了这个包，完全正常。然后在你的应用里，这里会卡死。我用的php artisan serve, 本地localhost:8000这样访问的.

**Comment by wmhello** [comment]
群里面有项目部署的视频 可以下来参考一下。
