### ISSUE TITLE
浏览器缓存问题

### ISSUE THREAD

**Issue by z289260161** [wmhello/laravel_template_with_vue#5]
使用Safari打开网站，第一次登陆正常，过几天登陆打不开网页。

此时卡在发送GET请求 "/api/user"，返回：
{
    "message": "Unauthenticated."
}

手动清除此网站的浏览器缓存后，恢复正常访问。

看起来似乎浏览器记住了登陆状态，但是token失效了，返回Unauthenticated，但是没有重新跳转到登录页面。

**Comment by kylesean** [comment]
@z289260161 AuthServiceProvider 里定义的token时间只有100分钟，太短了，可以尝试增大有效时间，然后到时间清理浏览器里的cookie里的token。作者应该忘了清token，导致过期了还用的老的token

**Comment by z289260161** [comment]
@kylesean 到期清理coolie里的token是一种办法，但是后端代码运行的时候出现error会刷新token，此时前端的cookie还是老的token。

我采用的办法是在 frontend/src/permission.js里改动，如果登录失败了自动跳转到登录页面。

**Comment by wmhello** [comment]
新的版本已经改变了这个内容  token失效会强制退出 
你说的这种情况原来是有的  谢谢你的反馈.
