### ISSUE TITLE
env('PASSPORT_CLIENT_SECRET')取值为null

### ISSUE THREAD

**Issue by liqigit** [wmhello/laravel_template_with_vue#7]
.env文件中已经配置PASSPORT_Client_Secret=pOTgujoROWXJidOezr4HRitRMUhvJARfsXRZ9PoE
但是在TokenProxy.php中public function proxy($grantType, array $data = [])方法中通过env('PASSPORT_CLIENT_SECRET')取得值为null，在tinker里命令行又可以正常取到这个配置值。。
请问这是怎么回事呢?

**Comment by wmhello** [comment]
估计是你本地的env配置有问题  多注意看看env文件
